#!/usr/bin/env python

from bioseq.calculation.Seqcal import *
from bioseq.pattern.Seqpattern import *
from bioseq.Seqman.dnaconvert import *
from main import main
import re, sys


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())















